name: app
type: golang:1.11
disk: 128

hooks:
  build: |
    set -eux
    time go get ./...
    # abort the build if generated code is not up-to-date
    if time go run ./internal/gen -path generated.go -exit-code; then
      echo "Generated code is out-of-date!" >&2
      exit 1
    fi
    time go build ./cmd/serve
    ls -l serve

mounts:
  /var/tmp:
    source: tmp
    source_path: tmpfiles
  /var/log:
    source: local
    source_path: logfiles

web:
  commands:
    start: ./serve

  upstream:
    socket_family: unix
    protocol: http

  locations:
    /:
      passthru: true
      allow: false
