// This file is generated by the ./internal/gen command -- do not edit!

package pshgo

import (
	"encoding/base64"
	"encoding/json"
	"fmt"

	errors "github.com/pkg/errors"
	logrus "github.com/sirupsen/logrus"
)

type AccessLevel uint8

const (
	AccessLevelViewer AccessLevel = iota
	AccessLevelContributor
	AccessLevelAdmin
	totalAccessLevels
)

var (
	accessLevels = [totalAccessLevels]string{
		"viewer",
		"contributor",
		"admin",
	}

	accessLevelsMap = map[string]AccessLevel{
		"viewer":      AccessLevelViewer,
		"contributor": AccessLevelContributor,
		"admin":       AccessLevelAdmin,
	}
)

func NewAccessLevel(name string) (AccessLevel, error) {
	if v, ok := accessLevelsMap[name]; ok {
		return v, nil
	}

	return 0, fmt.Errorf("unknown AccessLevel name %q", name)
}

func (v AccessLevel) String() string {
	if v < totalAccessLevels {
		return accessLevels[v]
	}

	return fmt.Sprintf("unknown AccessLevel value %02x", uint8(v))
}

func (v *AccessLevel) UnmarshalText(text []byte) (err error) {
	*v, err = NewAccessLevel(string(text))
	return err
}

func (v AccessLevel) MarshalText() ([]byte, error) {
	if v < totalAccessLevels {
		return []byte(accessLevels[v]), nil
	}

	return nil, errors.New(v.String())
}

type AccessType uint8

const (
	AccessTypeSSH AccessType = iota
	totalAccessTypes
)

var (
	accessTypes = [totalAccessTypes]string{
		"ssh",
	}

	accessTypesMap = map[string]AccessType{
		"ssh": AccessTypeSSH,
	}
)

func NewAccessType(name string) (AccessType, error) {
	if v, ok := accessTypesMap[name]; ok {
		return v, nil
	}

	return 0, fmt.Errorf("unknown AccessType name %q", name)
}

func (v AccessType) String() string {
	if v < totalAccessTypes {
		return accessTypes[v]
	}

	return fmt.Sprintf("unknown AccessType value %02x", uint8(v))
}

func (v *AccessType) UnmarshalText(text []byte) (err error) {
	*v, err = NewAccessType(string(text))
	return err
}

func (v AccessType) MarshalText() ([]byte, error) {
	if v < totalAccessTypes {
		return []byte(accessTypes[v]), nil
	}

	return nil, errors.New(v.String())
}

type ApplicationMount uint8

const (
	ApplicationMountLocal ApplicationMount = iota
	ApplicationMountTemp
	ApplicationMountService
	totalApplicationMounts
)

var (
	applicationMounts = [totalApplicationMounts]string{
		"local",
		"tmp",
		"service",
	}

	applicationMountsMap = map[string]ApplicationMount{
		"local":   ApplicationMountLocal,
		"tmp":     ApplicationMountTemp,
		"service": ApplicationMountService,
	}
)

func NewApplicationMount(name string) (ApplicationMount, error) {
	if v, ok := applicationMountsMap[name]; ok {
		return v, nil
	}

	return 0, fmt.Errorf("unknown ApplicationMount name %q", name)
}

func (v ApplicationMount) String() string {
	if v < totalApplicationMounts {
		return applicationMounts[v]
	}

	return fmt.Sprintf("unknown ApplicationMount value %02x", uint8(v))
}

func (v *ApplicationMount) UnmarshalText(text []byte) (err error) {
	*v, err = NewApplicationMount(string(text))
	return err
}

func (v ApplicationMount) MarshalText() ([]byte, error) {
	if v < totalApplicationMounts {
		return []byte(applicationMounts[v]), nil
	}

	return nil, errors.New(v.String())
}

type ServiceSize uint8

const (
	ServiceSizeAuto ServiceSize = iota
	ServiceSizeSmall
	ServiceSizeMedium
	ServiceSizeLarge
	ServiceSizeExtraLarge
	ServiceSizeDoubleExtraLarge
	ServiceSizeQuadrupleExtraLarge
	totalServiceSizes
)

var (
	serviceSizes = [totalServiceSizes]string{
		"AUTO",
		"S",
		"M",
		"L",
		"XL",
		"2XL",
		"4XL",
	}

	serviceSizesMap = map[string]ServiceSize{
		"AUTO": ServiceSizeAuto,
		"S":    ServiceSizeSmall,
		"M":    ServiceSizeMedium,
		"L":    ServiceSizeLarge,
		"XL":   ServiceSizeExtraLarge,
		"2XL":  ServiceSizeDoubleExtraLarge,
		"4XL":  ServiceSizeQuadrupleExtraLarge,
	}
)

func NewServiceSize(name string) (ServiceSize, error) {
	if v, ok := serviceSizesMap[name]; ok {
		return v, nil
	}

	return 0, fmt.Errorf("unknown ServiceSize name %q", name)
}

func (v ServiceSize) String() string {
	if v < totalServiceSizes {
		return serviceSizes[v]
	}

	return fmt.Sprintf("unknown ServiceSize value %02x", uint8(v))
}

func (v *ServiceSize) UnmarshalText(text []byte) (err error) {
	*v, err = NewServiceSize(string(text))
	return err
}

func (v ServiceSize) MarshalText() ([]byte, error) {
	if v < totalServiceSizes {
		return []byte(serviceSizes[v]), nil
	}

	return nil, errors.New(v.String())
}

type SocketFamily uint8

const (
	SocketFamilyTCP SocketFamily = iota
	SocketFamilyUnix
	totalSocketFamilies
)

var (
	socketFamilies = [totalSocketFamilies]string{
		"tcp",
		"unix",
	}

	socketFamiliesMap = map[string]SocketFamily{
		"tcp":  SocketFamilyTCP,
		"unix": SocketFamilyUnix,
	}
)

func NewSocketFamily(name string) (SocketFamily, error) {
	if v, ok := socketFamiliesMap[name]; ok {
		return v, nil
	}

	return 0, fmt.Errorf("unknown SocketFamily name %q", name)
}

func (v SocketFamily) String() string {
	if v < totalSocketFamilies {
		return socketFamilies[v]
	}

	return fmt.Sprintf("unknown SocketFamily value %02x", uint8(v))
}

func (v *SocketFamily) UnmarshalText(text []byte) (err error) {
	*v, err = NewSocketFamily(string(text))
	return err
}

func (v SocketFamily) MarshalText() ([]byte, error) {
	if v < totalSocketFamilies {
		return []byte(socketFamilies[v]), nil
	}

	return nil, errors.New(v.String())
}

type SocketProtocol uint8

const (
	SocketProtocolHTTP SocketProtocol = iota
	SocketProtocolFastCGI
	SocketProtocolUWSGI
	totalSocketProtocols
)

var (
	socketProtocols = [totalSocketProtocols]string{
		"http",
		"fastcgi",
		"uwsgi",
	}

	socketProtocolsMap = map[string]SocketProtocol{
		"http":    SocketProtocolHTTP,
		"fastcgi": SocketProtocolFastCGI,
		"uwsgi":   SocketProtocolUWSGI,
	}
)

func NewSocketProtocol(name string) (SocketProtocol, error) {
	if v, ok := socketProtocolsMap[name]; ok {
		return v, nil
	}

	return 0, fmt.Errorf("unknown SocketProtocol name %q", name)
}

func (v SocketProtocol) String() string {
	if v < totalSocketProtocols {
		return socketProtocols[v]
	}

	return fmt.Sprintf("unknown SocketProtocol value %02x", uint8(v))
}

func (v *SocketProtocol) UnmarshalText(text []byte) (err error) {
	*v, err = NewSocketProtocol(string(text))
	return err
}

func (v SocketProtocol) MarshalText() ([]byte, error) {
	if v < totalSocketProtocols {
		return []byte(socketProtocols[v]), nil
	}

	return nil, errors.New(v.String())
}

func GetApplication(p PlatformProvider) (*Application, bool) {
	name := p.Prefix() + "APPLICATION"
	value, ok := p.Lookup(name)
	if !ok {
		return nil, false
	}
	data, err := base64.StdEncoding.DecodeString(value)
	if err != nil {
		logrus.WithError(err).Warn("unable to decode value")
		return nil, false
	}
	obj := Application{}
	err = json.Unmarshal(data, &obj)
	if err != nil {
		logrus.WithError(err).Warn("unable to unmarshal value")
		return nil, false
	}
	return &obj, true
}

func MustGetApplication(p PlatformProvider) *Application {
	v, _ := GetApplication(p)
	return v
}

func (e *Environment) GetApplication() (*Application, bool) {
	return GetApplication(e)
}

func (e *Environment) MustGetApplication() *Application {
	return MustGetApplication(e)
}

func GetApplicationName(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "APPLICATION_NAME"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetApplicationName(p PlatformProvider) string {
	v, _ := GetApplicationName(p)
	return v
}

func (e *Environment) GetApplicationName() (string, bool) {
	return GetApplicationName(e)
}

func (e *Environment) MustGetApplicationName() string {
	return MustGetApplicationName(e)
}

func GetAppName(p PlatformProvider) (string, bool) {
	return GetApplicationName(p)
}

func MustGetAppName(p PlatformProvider) string {
	return MustGetApplicationName(p)
}

func (e *Environment) GetAppName() (string, bool) {
	return GetAppName(e)
}

func (e *Environment) MustGetAppName() string {
	return MustGetAppName(e)
}

func GetAppCommand(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "APP_COMMAND"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetAppCommand(p PlatformProvider) string {
	v, _ := GetAppCommand(p)
	return v
}

func (e *Environment) GetAppCommand() (string, bool) {
	return GetAppCommand(e)
}

func (e *Environment) MustGetAppCommand() string {
	return MustGetAppCommand(e)
}

func GetApplicationCommand(p PlatformProvider) (string, bool) {
	return GetAppCommand(p)
}

func MustGetApplicationCommand(p PlatformProvider) string {
	return MustGetAppCommand(p)
}

func (e *Environment) GetApplicationCommand() (string, bool) {
	return GetApplicationCommand(e)
}

func (e *Environment) MustGetApplicationCommand() string {
	return MustGetApplicationCommand(e)
}

func GetAppDir(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "APP_DIR"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetAppDir(p PlatformProvider) string {
	v, _ := GetAppDir(p)
	return v
}

func (e *Environment) GetAppDir() (string, bool) {
	return GetAppDir(e)
}

func (e *Environment) MustGetAppDir() string {
	return MustGetAppDir(e)
}

func GetBranch(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "BRANCH"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetBranch(p PlatformProvider) string {
	v, _ := GetBranch(p)
	return v
}

func (e *Environment) GetBranch() (string, bool) {
	return GetBranch(e)
}

func (e *Environment) MustGetBranch() string {
	return MustGetBranch(e)
}

func GetDir(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "DIR"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetDir(p PlatformProvider) string {
	v, _ := GetDir(p)
	return v
}

func (e *Environment) GetDir() (string, bool) {
	return GetDir(e)
}

func (e *Environment) MustGetDir() string {
	return MustGetDir(e)
}

func GetDocumentRoot(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "DOCUMENT_ROOT"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetDocumentRoot(p PlatformProvider) string {
	v, _ := GetDocumentRoot(p)
	return v
}

func (e *Environment) GetDocumentRoot() (string, bool) {
	return GetDocumentRoot(e)
}

func (e *Environment) MustGetDocumentRoot() string {
	return MustGetDocumentRoot(e)
}

func GetEnvironment(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "ENVIRONMENT"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetEnvironment(p PlatformProvider) string {
	v, _ := GetEnvironment(p)
	return v
}

func (e *Environment) GetEnvironment() (string, bool) {
	return GetEnvironment(e)
}

func (e *Environment) MustGetEnvironment() string {
	return MustGetEnvironment(e)
}

func GetPort(p PlatformProvider) (string, bool) {
	name := "PORT"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetPort(p PlatformProvider) string {
	v, _ := GetPort(p)
	return v
}

func (e *Environment) GetPort() (string, bool) {
	return GetPort(e)
}

func (e *Environment) MustGetPort() string {
	return MustGetPort(e)
}

func GetProject(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "PROJECT"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetProject(p PlatformProvider) string {
	v, _ := GetProject(p)
	return v
}

func (e *Environment) GetProject() (string, bool) {
	return GetProject(e)
}

func (e *Environment) MustGetProject() string {
	return MustGetProject(e)
}

func GetProjectEntropy(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "PROJECT_ENTROPY"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetProjectEntropy(p PlatformProvider) string {
	v, _ := GetProjectEntropy(p)
	return v
}

func (e *Environment) GetProjectEntropy() (string, bool) {
	return GetProjectEntropy(e)
}

func (e *Environment) MustGetProjectEntropy() string {
	return MustGetProjectEntropy(e)
}

func GetRelationships(p PlatformProvider) (Relationships, bool) {
	name := p.Prefix() + "RELATIONSHIPS"
	value, ok := p.Lookup(name)
	if !ok {
		return nil, false
	}
	data, err := base64.StdEncoding.DecodeString(value)
	if err != nil {
		logrus.WithError(err).Warn("unable to decode value")
		return nil, false
	}
	obj := Relationships{}
	err = json.Unmarshal(data, &obj)
	if err != nil {
		logrus.WithError(err).Warn("unable to unmarshal value")
		return nil, false
	}
	return obj, true
}

func MustGetRelationships(p PlatformProvider) Relationships {
	v, _ := GetRelationships(p)
	return v
}

func (e *Environment) GetRelationships() (Relationships, bool) {
	return GetRelationships(e)
}

func (e *Environment) MustGetRelationships() Relationships {
	return MustGetRelationships(e)
}

func GetRoutes(p PlatformProvider) (Routes, bool) {
	name := p.Prefix() + "ROUTES"
	value, ok := p.Lookup(name)
	if !ok {
		return nil, false
	}
	data, err := base64.StdEncoding.DecodeString(value)
	if err != nil {
		logrus.WithError(err).Warn("unable to decode value")
		return nil, false
	}
	obj := Routes{}
	err = json.Unmarshal(data, &obj)
	if err != nil {
		logrus.WithError(err).Warn("unable to unmarshal value")
		return nil, false
	}
	return obj, true
}

func MustGetRoutes(p PlatformProvider) Routes {
	v, _ := GetRoutes(p)
	return v
}

func (e *Environment) GetRoutes() (Routes, bool) {
	return GetRoutes(e)
}

func (e *Environment) MustGetRoutes() Routes {
	return MustGetRoutes(e)
}

func GetSMTPHost(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "SMTP_HOST"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetSMTPHost(p PlatformProvider) string {
	v, _ := GetSMTPHost(p)
	return v
}

func (e *Environment) GetSMTPHost() (string, bool) {
	return GetSMTPHost(e)
}

func (e *Environment) MustGetSMTPHost() string {
	return MustGetSMTPHost(e)
}

func GetSocket(p PlatformProvider) (string, bool) {
	name := "SOCKET"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetSocket(p PlatformProvider) string {
	v, _ := GetSocket(p)
	return v
}

func (e *Environment) GetSocket() (string, bool) {
	return GetSocket(e)
}

func (e *Environment) MustGetSocket() string {
	return MustGetSocket(e)
}

func GetTreeID(p PlatformProvider) (string, bool) {
	name := p.Prefix() + "TREE_ID"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetTreeID(p PlatformProvider) string {
	v, _ := GetTreeID(p)
	return v
}

func (e *Environment) GetTreeID() (string, bool) {
	return GetTreeID(e)
}

func (e *Environment) MustGetTreeID() string {
	return MustGetTreeID(e)
}

func GetVariables(p PlatformProvider) (Variables, bool) {
	name := p.Prefix() + "VARIABLES"
	value, ok := p.Lookup(name)
	if !ok {
		return nil, false
	}
	data, err := base64.StdEncoding.DecodeString(value)
	if err != nil {
		logrus.WithError(err).Warn("unable to decode value")
		return nil, false
	}
	obj := Variables{}
	err = json.Unmarshal(data, &obj)
	if err != nil {
		logrus.WithError(err).Warn("unable to unmarshal value")
		return nil, false
	}
	return obj, true
}

func MustGetVariables(p PlatformProvider) Variables {
	v, _ := GetVariables(p)
	return v
}

func (e *Environment) GetVariables() (Variables, bool) {
	return GetVariables(e)
}

func (e *Environment) MustGetVariables() Variables {
	return MustGetVariables(e)
}

func GetVars(p PlatformProvider) (Variables, bool) {
	return GetVariables(p)
}

func MustGetVars(p PlatformProvider) Variables {
	return MustGetVariables(p)
}

func (e *Environment) GetVars() (Variables, bool) {
	return GetVars(e)
}

func (e *Environment) MustGetVars() Variables {
	return MustGetVars(e)
}

func GetXClientCert(p PlatformProvider) (string, bool) {
	name := "X_CLIENT_CERT"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetXClientCert(p PlatformProvider) string {
	v, _ := GetXClientCert(p)
	return v
}

func (e *Environment) GetXClientCert() (string, bool) {
	return GetXClientCert(e)
}

func (e *Environment) MustGetXClientCert() string {
	return MustGetXClientCert(e)
}

func GetXClientDN(p PlatformProvider) (string, bool) {
	name := "X_CLIENT_DN"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetXClientDN(p PlatformProvider) string {
	v, _ := GetXClientDN(p)
	return v
}

func (e *Environment) GetXClientDN() (string, bool) {
	return GetXClientDN(e)
}

func (e *Environment) MustGetXClientDN() string {
	return MustGetXClientDN(e)
}

func GetXClientIP(p PlatformProvider) (string, bool) {
	name := "X_CLIENT_IP"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetXClientIP(p PlatformProvider) string {
	v, _ := GetXClientIP(p)
	return v
}

func (e *Environment) GetXClientIP() (string, bool) {
	return GetXClientIP(e)
}

func (e *Environment) MustGetXClientIP() string {
	return MustGetXClientIP(e)
}

func GetXClientVerify(p PlatformProvider) (string, bool) {
	name := "X_CLIENT_VERIFY"
	value, ok := p.Lookup(name)
	return value, ok
}

func MustGetXClientVerify(p PlatformProvider) string {
	v, _ := GetXClientVerify(p)
	return v
}

func (e *Environment) GetXClientVerify() (string, bool) {
	return GetXClientVerify(e)
}

func (e *Environment) MustGetXClientVerify() string {
	return MustGetXClientVerify(e)
}
